export const githubData = [
  {
    login: 'NickCraver',
    id: 454813,
    node_id: 'MDQ6VXNlcjQ1NDgxMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/454813?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/NickCraver',
    html_url: 'https://github.com/NickCraver',
    followers_url: 'https://api.github.com/users/NickCraver/followers',
    following_url:
      'https://api.github.com/users/NickCraver/following{/other_user}',
    gists_url: 'https://api.github.com/users/NickCraver/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/NickCraver/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/NickCraver/subscriptions',
    organizations_url: 'https://api.github.com/users/NickCraver/orgs',
    repos_url: 'https://api.github.com/users/NickCraver/repos',
    events_url: 'https://api.github.com/users/NickCraver/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/NickCraver/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'signalnerve',
    id: 922353,
    node_id: 'MDQ6VXNlcjkyMjM1Mw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/922353?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/signalnerve',
    html_url: 'https://github.com/signalnerve',
    followers_url: 'https://api.github.com/users/signalnerve/followers',
    following_url:
      'https://api.github.com/users/signalnerve/following{/other_user}',
    gists_url: 'https://api.github.com/users/signalnerve/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/signalnerve/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/signalnerve/subscriptions',
    organizations_url: 'https://api.github.com/users/signalnerve/orgs',
    repos_url: 'https://api.github.com/users/signalnerve/repos',
    events_url: 'https://api.github.com/users/signalnerve/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/signalnerve/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'benaadams',
    id: 1142958,
    node_id: 'MDQ6VXNlcjExNDI5NTg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1142958?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/benaadams',
    html_url: 'https://github.com/benaadams',
    followers_url: 'https://api.github.com/users/benaadams/followers',
    following_url:
      'https://api.github.com/users/benaadams/following{/other_user}',
    gists_url: 'https://api.github.com/users/benaadams/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/benaadams/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/benaadams/subscriptions',
    organizations_url: 'https://api.github.com/users/benaadams/orgs',
    repos_url: 'https://api.github.com/users/benaadams/repos',
    events_url: 'https://api.github.com/users/benaadams/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/benaadams/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Sput',
    id: 1197741,
    node_id: 'MDQ6VXNlcjExOTc3NDE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1197741?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Sput',
    html_url: 'https://github.com/Sput',
    followers_url: 'https://api.github.com/users/Sput/followers',
    following_url: 'https://api.github.com/users/Sput/following{/other_user}',
    gists_url: 'https://api.github.com/users/Sput/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Sput/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Sput/subscriptions',
    organizations_url: 'https://api.github.com/users/Sput/orgs',
    repos_url: 'https://api.github.com/users/Sput/repos',
    events_url: 'https://api.github.com/users/Sput/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Sput/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JLLeitschuh',
    id: 1323708,
    node_id: 'MDQ6VXNlcjEzMjM3MDg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1323708?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JLLeitschuh',
    html_url: 'https://github.com/JLLeitschuh',
    followers_url: 'https://api.github.com/users/JLLeitschuh/followers',
    following_url:
      'https://api.github.com/users/JLLeitschuh/following{/other_user}',
    gists_url: 'https://api.github.com/users/JLLeitschuh/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/JLLeitschuh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JLLeitschuh/subscriptions',
    organizations_url: 'https://api.github.com/users/JLLeitschuh/orgs',
    repos_url: 'https://api.github.com/users/JLLeitschuh/repos',
    events_url: 'https://api.github.com/users/JLLeitschuh/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/JLLeitschuh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'codyseibert',
    id: 1868782,
    node_id: 'MDQ6VXNlcjE4Njg3ODI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1868782?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/codyseibert',
    html_url: 'https://github.com/codyseibert',
    followers_url: 'https://api.github.com/users/codyseibert/followers',
    following_url:
      'https://api.github.com/users/codyseibert/following{/other_user}',
    gists_url: 'https://api.github.com/users/codyseibert/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/codyseibert/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/codyseibert/subscriptions',
    organizations_url: 'https://api.github.com/users/codyseibert/orgs',
    repos_url: 'https://api.github.com/users/codyseibert/repos',
    events_url: 'https://api.github.com/users/codyseibert/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/codyseibert/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'bhague1281',
    id: 1969764,
    node_id: 'MDQ6VXNlcjE5Njk3NjQ=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1969764?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bhague1281',
    html_url: 'https://github.com/bhague1281',
    followers_url: 'https://api.github.com/users/bhague1281/followers',
    following_url:
      'https://api.github.com/users/bhague1281/following{/other_user}',
    gists_url: 'https://api.github.com/users/bhague1281/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/bhague1281/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/bhague1281/subscriptions',
    organizations_url: 'https://api.github.com/users/bhague1281/orgs',
    repos_url: 'https://api.github.com/users/bhague1281/repos',
    events_url: 'https://api.github.com/users/bhague1281/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/bhague1281/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kamranahmedse',
    id: 4921183,
    node_id: 'MDQ6VXNlcjQ5MjExODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/4921183?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kamranahmedse',
    html_url: 'https://github.com/kamranahmedse',
    followers_url: 'https://api.github.com/users/kamranahmedse/followers',
    following_url:
      'https://api.github.com/users/kamranahmedse/following{/other_user}',
    gists_url: 'https://api.github.com/users/kamranahmedse/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/kamranahmedse/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/kamranahmedse/subscriptions',
    organizations_url: 'https://api.github.com/users/kamranahmedse/orgs',
    repos_url: 'https://api.github.com/users/kamranahmedse/repos',
    events_url: 'https://api.github.com/users/kamranahmedse/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/kamranahmedse/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'azocher',
    id: 10081635,
    node_id: 'MDQ6VXNlcjEwMDgxNjM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/10081635?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/azocher',
    html_url: 'https://github.com/azocher',
    followers_url: 'https://api.github.com/users/azocher/followers',
    following_url:
      'https://api.github.com/users/azocher/following{/other_user}',
    gists_url: 'https://api.github.com/users/azocher/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/azocher/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/azocher/subscriptions',
    organizations_url: 'https://api.github.com/users/azocher/orgs',
    repos_url: 'https://api.github.com/users/azocher/repos',
    events_url: 'https://api.github.com/users/azocher/events{/privacy}',
    received_events_url: 'https://api.github.com/users/azocher/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'romebell',
    id: 13144457,
    node_id: 'MDQ6VXNlcjEzMTQ0NDU3',
    avatar_url: 'https://avatars.githubusercontent.com/u/13144457?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/romebell',
    html_url: 'https://github.com/romebell',
    followers_url: 'https://api.github.com/users/romebell/followers',
    following_url:
      'https://api.github.com/users/romebell/following{/other_user}',
    gists_url: 'https://api.github.com/users/romebell/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/romebell/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/romebell/subscriptions',
    organizations_url: 'https://api.github.com/users/romebell/orgs',
    repos_url: 'https://api.github.com/users/romebell/repos',
    events_url: 'https://api.github.com/users/romebell/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/romebell/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'brandiw',
    id: 18649209,
    node_id: 'MDQ6VXNlcjE4NjQ5MjA5',
    avatar_url: 'https://avatars.githubusercontent.com/u/18649209?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/brandiw',
    html_url: 'https://github.com/brandiw',
    followers_url: 'https://api.github.com/users/brandiw/followers',
    following_url:
      'https://api.github.com/users/brandiw/following{/other_user}',
    gists_url: 'https://api.github.com/users/brandiw/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/brandiw/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/brandiw/subscriptions',
    organizations_url: 'https://api.github.com/users/brandiw/orgs',
    repos_url: 'https://api.github.com/users/brandiw/repos',
    events_url: 'https://api.github.com/users/brandiw/events{/privacy}',
    received_events_url: 'https://api.github.com/users/brandiw/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jshawndunn',
    id: 20318945,
    node_id: 'MDQ6VXNlcjIwMzE4OTQ1',
    avatar_url: 'https://avatars.githubusercontent.com/u/20318945?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jshawndunn',
    html_url: 'https://github.com/jshawndunn',
    followers_url: 'https://api.github.com/users/jshawndunn/followers',
    following_url:
      'https://api.github.com/users/jshawndunn/following{/other_user}',
    gists_url: 'https://api.github.com/users/jshawndunn/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jshawndunn/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jshawndunn/subscriptions',
    organizations_url: 'https://api.github.com/users/jshawndunn/orgs',
    repos_url: 'https://api.github.com/users/jshawndunn/repos',
    events_url: 'https://api.github.com/users/jshawndunn/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jshawndunn/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'miguelapou',
    id: 20328334,
    node_id: 'MDQ6VXNlcjIwMzI4MzM0',
    avatar_url: 'https://avatars.githubusercontent.com/u/20328334?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/miguelapou',
    html_url: 'https://github.com/miguelapou',
    followers_url: 'https://api.github.com/users/miguelapou/followers',
    following_url:
      'https://api.github.com/users/miguelapou/following{/other_user}',
    gists_url: 'https://api.github.com/users/miguelapou/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/miguelapou/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/miguelapou/subscriptions',
    organizations_url: 'https://api.github.com/users/miguelapou/orgs',
    repos_url: 'https://api.github.com/users/miguelapou/repos',
    events_url: 'https://api.github.com/users/miguelapou/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/miguelapou/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: '009Kings',
    id: 29936437,
    node_id: 'MDQ6VXNlcjI5OTM2NDM3',
    avatar_url: 'https://avatars.githubusercontent.com/u/29936437?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/009Kings',
    html_url: 'https://github.com/009Kings',
    followers_url: 'https://api.github.com/users/009Kings/followers',
    following_url:
      'https://api.github.com/users/009Kings/following{/other_user}',
    gists_url: 'https://api.github.com/users/009Kings/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/009Kings/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/009Kings/subscriptions',
    organizations_url: 'https://api.github.com/users/009Kings/orgs',
    repos_url: 'https://api.github.com/users/009Kings/repos',
    events_url: 'https://api.github.com/users/009Kings/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/009Kings/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'TaylorDarneille',
    id: 33237160,
    node_id: 'MDQ6VXNlcjMzMjM3MTYw',
    avatar_url: 'https://avatars.githubusercontent.com/u/33237160?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/TaylorDarneille',
    html_url: 'https://github.com/TaylorDarneille',
    followers_url: 'https://api.github.com/users/TaylorDarneille/followers',
    following_url:
      'https://api.github.com/users/TaylorDarneille/following{/other_user}',
    gists_url: 'https://api.github.com/users/TaylorDarneille/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/TaylorDarneille/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/TaylorDarneille/subscriptions',
    organizations_url: 'https://api.github.com/users/TaylorDarneille/orgs',
    repos_url: 'https://api.github.com/users/TaylorDarneille/repos',
    events_url: 'https://api.github.com/users/TaylorDarneille/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/TaylorDarneille/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'john-smilga',
    id: 42133389,
    node_id: 'MDQ6VXNlcjQyMTMzMzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/42133389?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/john-smilga',
    html_url: 'https://github.com/john-smilga',
    followers_url: 'https://api.github.com/users/john-smilga/followers',
    following_url:
      'https://api.github.com/users/john-smilga/following{/other_user}',
    gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
    organizations_url: 'https://api.github.com/users/john-smilga/orgs',
    repos_url: 'https://api.github.com/users/john-smilga/repos',
    events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/john-smilga/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'omunoz-89',
    id: 49264189,
    node_id: 'MDQ6VXNlcjQ5MjY0MTg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/49264189?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/omunoz-89',
    html_url: 'https://github.com/omunoz-89',
    followers_url: 'https://api.github.com/users/omunoz-89/followers',
    following_url:
      'https://api.github.com/users/omunoz-89/following{/other_user}',
    gists_url: 'https://api.github.com/users/omunoz-89/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/omunoz-89/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/omunoz-89/subscriptions',
    organizations_url: 'https://api.github.com/users/omunoz-89/orgs',
    repos_url: 'https://api.github.com/users/omunoz-89/repos',
    events_url: 'https://api.github.com/users/omunoz-89/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/omunoz-89/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kubowania',
    id: 51362610,
    node_id: 'MDQ6VXNlcjUxMzYyNjEw',
    avatar_url: 'https://avatars.githubusercontent.com/u/51362610?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kubowania',
    html_url: 'https://github.com/kubowania',
    followers_url: 'https://api.github.com/users/kubowania/followers',
    following_url:
      'https://api.github.com/users/kubowania/following{/other_user}',
    gists_url: 'https://api.github.com/users/kubowania/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/kubowania/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kubowania/subscriptions',
    organizations_url: 'https://api.github.com/users/kubowania/orgs',
    repos_url: 'https://api.github.com/users/kubowania/repos',
    events_url: 'https://api.github.com/users/kubowania/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/kubowania/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'charlenebatiste',
    id: 67442041,
    node_id: 'MDQ6VXNlcjY3NDQyMDQx',
    avatar_url: 'https://avatars.githubusercontent.com/u/67442041?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/charlenebatiste',
    html_url: 'https://github.com/charlenebatiste',
    followers_url: 'https://api.github.com/users/charlenebatiste/followers',
    following_url:
      'https://api.github.com/users/charlenebatiste/following{/other_user}',
    gists_url: 'https://api.github.com/users/charlenebatiste/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/charlenebatiste/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/charlenebatiste/subscriptions',
    organizations_url: 'https://api.github.com/users/charlenebatiste/orgs',
    repos_url: 'https://api.github.com/users/charlenebatiste/repos',
    events_url: 'https://api.github.com/users/charlenebatiste/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/charlenebatiste/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'brandonhall96',
    id: 73011352,
    node_id: 'MDQ6VXNlcjczMDExMzUy',
    avatar_url: 'https://avatars.githubusercontent.com/u/73011352?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/brandonhall96',
    html_url: 'https://github.com/brandonhall96',
    followers_url: 'https://api.github.com/users/brandonhall96/followers',
    following_url:
      'https://api.github.com/users/brandonhall96/following{/other_user}',
    gists_url: 'https://api.github.com/users/brandonhall96/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/brandonhall96/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/brandonhall96/subscriptions',
    organizations_url: 'https://api.github.com/users/brandonhall96/orgs',
    repos_url: 'https://api.github.com/users/brandonhall96/repos',
    events_url: 'https://api.github.com/users/brandonhall96/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/brandonhall96/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'aprin418',
    id: 77419893,
    node_id: 'MDQ6VXNlcjc3NDE5ODkz',
    avatar_url: 'https://avatars.githubusercontent.com/u/77419893?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/aprin418',
    html_url: 'https://github.com/aprin418',
    followers_url: 'https://api.github.com/users/aprin418/followers',
    following_url:
      'https://api.github.com/users/aprin418/following{/other_user}',
    gists_url: 'https://api.github.com/users/aprin418/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/aprin418/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/aprin418/subscriptions',
    organizations_url: 'https://api.github.com/users/aprin418/orgs',
    repos_url: 'https://api.github.com/users/aprin418/repos',
    events_url: 'https://api.github.com/users/aprin418/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/aprin418/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'evan-woodworth',
    id: 80374875,
    node_id: 'MDQ6VXNlcjgwMzc0ODc1',
    avatar_url: 'https://avatars.githubusercontent.com/u/80374875?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/evan-woodworth',
    html_url: 'https://github.com/evan-woodworth',
    followers_url: 'https://api.github.com/users/evan-woodworth/followers',
    following_url:
      'https://api.github.com/users/evan-woodworth/following{/other_user}',
    gists_url: 'https://api.github.com/users/evan-woodworth/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/evan-woodworth/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/evan-woodworth/subscriptions',
    organizations_url: 'https://api.github.com/users/evan-woodworth/orgs',
    repos_url: 'https://api.github.com/users/evan-woodworth/repos',
    events_url: 'https://api.github.com/users/evan-woodworth/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/evan-woodworth/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'anthonymang',
    id: 80987583,
    node_id: 'MDQ6VXNlcjgwOTg3NTgz',
    avatar_url: 'https://avatars.githubusercontent.com/u/80987583?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/anthonymang',
    html_url: 'https://github.com/anthonymang',
    followers_url: 'https://api.github.com/users/anthonymang/followers',
    following_url:
      'https://api.github.com/users/anthonymang/following{/other_user}',
    gists_url: 'https://api.github.com/users/anthonymang/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/anthonymang/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/anthonymang/subscriptions',
    organizations_url: 'https://api.github.com/users/anthonymang/orgs',
    repos_url: 'https://api.github.com/users/anthonymang/repos',
    events_url: 'https://api.github.com/users/anthonymang/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/anthonymang/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'amanda-posey',
    id: 81441909,
    node_id: 'MDQ6VXNlcjgxNDQxOTA5',
    avatar_url: 'https://avatars.githubusercontent.com/u/81441909?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/amanda-posey',
    html_url: 'https://github.com/amanda-posey',
    followers_url: 'https://api.github.com/users/amanda-posey/followers',
    following_url:
      'https://api.github.com/users/amanda-posey/following{/other_user}',
    gists_url: 'https://api.github.com/users/amanda-posey/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/amanda-posey/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/amanda-posey/subscriptions',
    organizations_url: 'https://api.github.com/users/amanda-posey/orgs',
    repos_url: 'https://api.github.com/users/amanda-posey/repos',
    events_url: 'https://api.github.com/users/amanda-posey/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/amanda-posey/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'behemoth0132',
    id: 81875454,
    node_id: 'MDQ6VXNlcjgxODc1NDU0',
    avatar_url: 'https://avatars.githubusercontent.com/u/81875454?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/behemoth0132',
    html_url: 'https://github.com/behemoth0132',
    followers_url: 'https://api.github.com/users/behemoth0132/followers',
    following_url:
      'https://api.github.com/users/behemoth0132/following{/other_user}',
    gists_url: 'https://api.github.com/users/behemoth0132/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/behemoth0132/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/behemoth0132/subscriptions',
    organizations_url: 'https://api.github.com/users/behemoth0132/orgs',
    repos_url: 'https://api.github.com/users/behemoth0132/repos',
    events_url: 'https://api.github.com/users/behemoth0132/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/behemoth0132/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jakeschultz89',
    id: 81945834,
    node_id: 'MDQ6VXNlcjgxOTQ1ODM0',
    avatar_url: 'https://avatars.githubusercontent.com/u/81945834?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jakeschultz89',
    html_url: 'https://github.com/jakeschultz89',
    followers_url: 'https://api.github.com/users/jakeschultz89/followers',
    following_url:
      'https://api.github.com/users/jakeschultz89/following{/other_user}',
    gists_url: 'https://api.github.com/users/jakeschultz89/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jakeschultz89/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/jakeschultz89/subscriptions',
    organizations_url: 'https://api.github.com/users/jakeschultz89/orgs',
    repos_url: 'https://api.github.com/users/jakeschultz89/repos',
    events_url: 'https://api.github.com/users/jakeschultz89/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jakeschultz89/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noncenze',
    id: 82400098,
    node_id: 'MDQ6VXNlcjgyNDAwMDk4',
    avatar_url: 'https://avatars.githubusercontent.com/u/82400098?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noncenze',
    html_url: 'https://github.com/noncenze',
    followers_url: 'https://api.github.com/users/noncenze/followers',
    following_url:
      'https://api.github.com/users/noncenze/following{/other_user}',
    gists_url: 'https://api.github.com/users/noncenze/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/noncenze/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noncenze/subscriptions',
    organizations_url: 'https://api.github.com/users/noncenze/orgs',
    repos_url: 'https://api.github.com/users/noncenze/repos',
    events_url: 'https://api.github.com/users/noncenze/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noncenze/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mauricechevez',
    id: 82402602,
    node_id: 'MDQ6VXNlcjgyNDAyNjAy',
    avatar_url: 'https://avatars.githubusercontent.com/u/82402602?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mauricechevez',
    html_url: 'https://github.com/mauricechevez',
    followers_url: 'https://api.github.com/users/mauricechevez/followers',
    following_url:
      'https://api.github.com/users/mauricechevez/following{/other_user}',
    gists_url: 'https://api.github.com/users/mauricechevez/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mauricechevez/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/mauricechevez/subscriptions',
    organizations_url: 'https://api.github.com/users/mauricechevez/orgs',
    repos_url: 'https://api.github.com/users/mauricechevez/repos',
    events_url: 'https://api.github.com/users/mauricechevez/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mauricechevez/received_events',
    type: 'User',
    site_admin: false,
  },
]
